In [1]:
import numpy as np


In [2]:
a = np.array([1, 2, 3])

In [3]:
b = np.array([(1.5, 2, 3), (4, 5, 6)], dtype = float)

In [4]:
c = np.array([[(1.5, 2, 3), (4, 5, 6)], [(3, 2, 1), (4, 5, 6)]], dtype = float)

In [5]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2, 3, 4), dtype = np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [7]:
d = np.arange(10, 25, 5)

In [8]:
d

array([10, 15, 20])

In [9]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [10]:
np.full((2, 2), 7)

array([[7, 7],
       [7, 7]])

In [11]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [12]:
np.random.random((2, 2)

_IncompleteInputError: incomplete input (2887226526.py, line 1)

In [13]:
np.random.random((2, 2))

array([[0.35557034, 0.84576268],
       [0.29345425, 0.694241  ]])

In [14]:
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [16]:
c.shape

(2, 2, 3)

In [17]:
a.ndim

1

In [18]:
b.ndim

2

In [19]:
c.ndim

3

In [20]:
a.size

3

In [21]:
b.size

6

In [22]:
c.size

12

In [23]:
b.dtype

dtype('float64')

In [24]:
b.dtype.name

'float64'

In [25]:
b.astype(int)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.add(a, b)

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [27]:
np.subtract(a, b)

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [28]:
np.multiply(b, b)

array([[ 2.25,  4.  ,  9.  ],
       [16.  , 25.  , 36.  ]])

In [29]:
np.divide(b, b)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081])

In [31]:
a.sum()

np.int64(6)

In [32]:
a.min()

np.int64(1)

In [33]:
a.max()

np.int64(3)

In [34]:
b.cumsum()

array([ 1.5,  3.5,  6.5, 10.5, 15.5, 21.5])

In [35]:
a.mean()

np.float64(2.0)

In [36]:
a.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [37]:
b.median()

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [38]:
np.std(b)

np.float64(1.5920810978785667)